### ISSUE TITLE
Making Selected Segment Shape Square

### ISSUE THREAD

**Issue by i-asimkhan** [spirosrap/insta#1]
Hello 
Firstly, your awesome work had great charm for me.

I want to make the selected segment shape from rounded to square !

How could I do this?

**Comment by spirosrap** [comment]
Hello, 

Sorry for the late reply!

It's really easy to customize the segmented control. 

I followed [this](http://www.appdesignvault.com/custom-segmented-control-swift-tutorial/) tutorial when I developed the app.

In line 72 (File **ADVSegmentedControl.swift**) change the corner radius as:

```
layer.cornerRadius = frame.height / 15
```

And in line 117

```
thumbView.layer.cornerRadius = thumbView.frame.height / 15
```
